---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pyapp
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/pyapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: pyapp-source

